### ISSUE TITLE
deposit report/interest payment report

### ISSUE THREAD

**Issue by pestest** [nabinked/everest-test#25]
Server Error in '/' Application.

The resource cannot be found.

Description: HTTP 404. The resource you are looking for (or one of its dependencies) could have been removed, had its name changed, or is temporarily unavailable.  Please review the following URL and make sure that it is spelled correctly. 

Requested URL: /Report/Deposit/InterestPaymentReport.aspx

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.0.30319.18408

error aayo

**Comment by mban94** [comment]
Solved
