### ISSUE TITLE
Setup>Share Setup>Share Products.. Products Not Delete..

### ISSUE THREAD

**Issue by nishankn** [nabinked/everest-test#32]
http://everest.planetearthsolution.com/Setup/Banking/ShareProducts.aspx
Share Product select garera delete button click garda <Are You Sure? vanne msg falxa. ani tesma ok garda task completed succesfully vanxa. but share product delete hudaina...

**Comment by mban94** [comment]
Share Product ma account create bhaesake pachi product delete garna mildaena, tyai bhako hola.
