### ISSUE TITLE
loan report / loan receipts

### ISSUE THREAD

**Issue by pestest** [nabinked/everest-test#36]
Server Error in '/' Application.

ERROR: 23503: insert or update on table "report_queries" violates foreign key constraint "report_queries_user_id_fkey"

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: Npgsql.NpgsqlException: ERROR: 23503: insert or update on table "report_queries" violates foreign key constraint "report_queries_user_id_fkey"

Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace: 

[NpgsqlException (0x80004005): ERROR: 23503: insert or update on table "report_queries" violates foreign key constraint "report_queries_user_id_fkey"]
   Npgsql.<ProcessBackendResponses>d__0.MoveNext() +418
   Npgsql.ForwardsOnlyDataReader.GetNextResponseObject(Boolean cleanup) +469
   Npgsql.ForwardsOnlyDataReader.GetNextRowDescription() +79
   Npgsql.ForwardsOnlyDataReader.NextResultInternal() +63
   Npgsql.ForwardsOnlyDataReader..ctor(IEnumerable`1 dataEnumeration, CommandBehavior behavior, NpgsqlCommand command, NotificationThreadBlock threadBlock, Boolean preparedStatement, NpgsqlRowDescription rowDescription) +138
   Npgsql.NpgsqlCommand.GetReader(CommandBehavior cb) +301
   Npgsql.NpgsqlCommand.ExecuteNonQuery() +66
   Everest.Net.DatabaseLayer.DBFactory.DBOperations.ExecuteNonQuery(NpgsqlCommand command) +98
   Everest.Net.DatabaseLayer.Reports.ReportParameter.InsertReportParameter(ReportParameter reportParameter) +264
   Everest.Net.BusinessLayer.Reports.ReportParameter.InsertReportQuery(Int32 userId, String query, String style, String title, String reportType, String highlightHead) +138
   Everest.Net.Web.Report.Loan.LoanReceipts.ShowButton_Click(Object sender, EventArgs e) +964
   System.Web.UI.WebControls.LinkButton.OnClick(EventArgs e) +116
   System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument) +101
   System.Web.UI.WebControls.LinkButton.System.Web.UI.IPostBackEventHandler.RaisePostBackEvent(String eventArgument) +10
   System.Web.UI.Page.RaisePostBackEvent(IPostBackEventHandler sourceControl, String eventArgument) +13
   System.Web.UI.Page.RaisePostBackEvent(NameValueCollection postData) +9528578
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +1724

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.0.30319.18408

**Comment by mban94** [comment]
This error is caused by user login, if your login session expires then you get such error. Log out from system and login again.
