### ISSUE TITLE
Share Ledger Add new Problem.. 

### ISSUE THREAD

**Issue by nishankn** [nabinked/everest-test#48]
http://everest.planetearthsolution.com/Setup/Ledgers/ShareLedger.aspx
Share ledger Issue nai vayena. Yo msg. diyo

Server Error in '/' Application.

ERROR: 22P02: invalid input syntax for integer: "DhaniHaru"

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: Npgsql.NpgsqlException: ERROR: 22P02: invalid input syntax for integer: "DhaniHaru"

Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace: 

[NpgsqlException (0x80004005): ERROR: 22P02: invalid input syntax for integer: "DhaniHaru"]
   Npgsql.<ProcessBackendResponses>d__0.MoveNext() +418
   Npgsql.ForwardsOnlyDataReader.GetNextResponseObject(Boolean cleanup) +469
   Npgsql.ForwardsOnlyDataReader.GetNextRow(Boolean clearPending) +241
   Npgsql.ForwardsOnlyDataReader.Read() +39
   Npgsql.NpgsqlCommand.ExecuteScalar() +47
   Everest.Net.DatabaseLayer.DBFactory.DBOperations.GetScalarValue(NpgsqlCommand command) +98
   Everest.Net.DatabaseLayer.Core.ShareAccounts.GetMaxAccountNumber(String prefix, String suffix) +185
   Everest.Net.BusinessLayer.Core.ShareAccounts.GetMaxAccountNumber(String prefix, String suffix) +48
   Everest.Net.Web.Setup.Ledgers.ShareLedger.ShareAccountGroupDropDownList_SelectedIndexChanged(Object sender, EventArgs e) +376
   System.Web.UI.WebControls.ListControl.OnSelectedIndexChanged(EventArgs e) +116
   System.Web.UI.WebControls.DropDownList.RaisePostDataChangedEvent() +133
   System.Web.UI.WebControls.DropDownList.System.Web.UI.IPostBackDataHandler.RaisePostDataChangedEvent() +13
   System.Web.UI.Page.RaiseChangedEvents() +132
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +1644

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.0.30319.18408

**Comment by mban94** [comment]
Solved
