### ISSUE TITLE
Customer entry problem..

### ISSUE THREAD

**Issue by nishankn** [nabinked/everest-test#49]
http://everest.planetearthsolution.com/Transactions/AddNewCustomer.aspx

add new customer garda ni error dekhayo.. 
Server Error in '/' Application.

ERROR: 23505: duplicate key value violates unique constraint "non_corporate_customers_pkey"

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: Npgsql.NpgsqlException: ERROR: 23505: duplicate key value violates unique constraint "non_corporate_customers_pkey"

**Comment by mban94** [comment]
Solved
