### ISSUE TITLE
office setup issues

### ISSUE THREAD

**Issue by angelsapkota** [nabinked/everest-test#7]
**office setup**

1) Office Setup :- 
*  registration date lidaina.. hamile j lekheny 01/01/0001 dekhauxa

2) fiscal year setup :-
*  fiscal year setup ek choti banaye paxi edit garna mildaina.

#) cash repository :-
* cash repository create garda parent repository ma select repository bhanera matrai dekhauxa 
kunai select garne option nai dekhaudaina.

4) unit setup :-
* unit setup ko front phase ma hamile create gareko madhye unit co-ordinator ko name dekhaudaina.. sayad side scrolling 
option nabhayeko ho ki tyastai ho tyo.

5) parameter :-
* charkhata setup ma search option bata search garda search nai hudaina.

**Comment by nabinked** [comment]
office setup solved

**Comment by nabinked** [comment]
3 - Cash reporitory ma Cash storage no bhako matra parent ma dekhauchha tehi bhayera na dekhako ho. Euta naya cash reporisory banaunu jasma cash storage no garera banaunu hos ani balla dekhauhha

**Comment by nabinked** [comment]
2 - Fiscal year setup edit garna na milakai thik ho ahile ko laagi

**Comment by nabinked** [comment]
5 grid view ma unit coordinator ko display option rakheko chhaina. not an issue
