### ISSUE TITLE
Office Setup OfficeID 1 chahi edit garna milena

### ISSUE THREAD

**Issue by nishankn** [nabinked/everest-test#70]
http://everest.planetearthsolution.com/Setup/Office/OfficeSetup.aspx
Setup > Office Setup > Office Setup ma gayera Office ID 1 ko chahi edit garna milena.. Aru milxa.
Problem..
Server Error in '/' Application.

'ParentOfficeDropDownList' has a SelectedValue which is invalid because it does not exist in the list of items.
Parameter name: value 

Ki yo edit garnai namilne ho ra..

**Comment by nabinked** [comment]
FIxed
