### ISSUE TITLE
Setup > Office Setup > Fiscal Year Setup ma edit option nachaleko

### ISSUE THREAD

**Issue by nishankn** [nabinked/everest-test#72]
http://everest.planetearthsolution.com/Setup/Office/FiscalYearSetup.aspx

Fiscal year setup ma edit option click garna milena. ra fiscal year select garda sab select hunxa. euta fiscal year select garera arko ma select garda tyo ni select hunxa..

**Comment by nabinked** [comment]
Not allowed right now
