### ISSUE TITLE
Customer Report Print Button click garda hang issue...

### ISSUE THREAD

**Issue by nishankn** [nabinked/everest-test#87]
http://everest.planetearthsolution.com/Report/Customer/CustomersView.aspx
Reports>Customer Reports>Customer View ma gayera print button click garda new tab ma print preview dekhauxa. but tyo customer view wala tab purai hang hunxa. Print ra Export Button ni gayab hunxa plus aru function pani kaam gardaina..

**Comment by nabinked** [comment]
fixed
