### ISSUE TITLE
loan reimburse

### ISSUE THREAD

**Issue by pestest** [nabinked/everest-test#91]
LoanReimburse.aspx:388 GET http://everest.planetearthsolution.com/fonts/fontawesome-webfont.woff?v=4.2.0 
LoanReimburse.aspx:388 GET http://everest.planetearthsolution.com/fonts/glyphicons-halflings-regular.woff 
master-page.js:2 [prevObject: i.fn.init[1], context: document, selector: "i.fa.fa-gear", jquery: "2.1.3", constructor: function…]
master-page.js:8 /Transactions/Loan/LoanReimburse.aspx
master-page.js:11 [a.with-url, prevObject: n.fn.init[1], context: document, jquery: "2.1.3", constructor: function, selector: ""…]
signalr?v=y_4IpeeDdgoHqAhjqu2f3QsBnP-e4GuBLMt7WpNZnIM1:1 [11:22:06 GMT+0545 (Nepal Standard Time)] SignalR: Client subscribed to hub 'notificationshub'.
signalr?v=y_4IpeeDdgoHqAhjqu2f3QsBnP-e4GuBLMt7WpNZnIM1:1 [11:22:06 GMT+0545 (Nepal Standard Time)] SignalR: Negotiating with '/signalr/negotiate?clientProtocol=1.5&connectionData=%5B%7B%22name%22%3A%22notificationshub%22%7D%5D'.
signalr?v=y_4IpeeDdgoHqAhjqu2f3QsBnP-e4GuBLMt7WpNZnIM1:1 [11:22:06 GMT+0545 (Nepal Standard Time)] SignalR: serverSentEvents transport starting.
signalr?v=y_4IpeeDdgoHqAhjqu2f3QsBnP-e4GuBLMt7WpNZnIM1:1 [11:22:06 GMT+0545 (Nepal Standard Time)] SignalR: Attempting to connect to SSE endpoint 'http://everest.planetearthsolution.com/signalr/connect?transport=serverSent…Khneh&connectionData=%5B%7B%22name%22%3A%22notificationshub%22%7D%5D&tid=3'.
signalr?v=y_4IpeeDdgoHqAhjqu2f3QsBnP-e4GuBLMt7WpNZnIM1:1 [11:22:06 GMT+0545 (Nepal Standard Time)] SignalR: EventSource connected.
signalr?v=y_4IpeeDdgoHqAhjqu2f3QsBnP-e4GuBLMt7WpNZnIM1:1 [11:22:06 GMT+0545 (Nepal Standard Time)] SignalR: serverSentEvents transport connected. Initiating start request.
signalr?v=y_4IpeeDdgoHqAhjqu2f3QsBnP-e4GuBLMt7WpNZnIM1:1 [11:22:06 GMT+0545 (Nepal Standard Time)] SignalR: The start request succeeded. Transitioning to the connected state.
signalr?v=y_4IpeeDdgoHqAhjqu2f3QsBnP-e4GuBLMt7WpNZnIM1:1 [11:22:06 GMT+0545 (Nepal Standard Time)] SignalR: Now monitoring keep alive with a warning timeout of 13333.333333333332, keep alive timeout of 20000 and disconnecting timeout of 30000
signalr?v=y_4IpeeDdgoHqAhjqu2f3QsBnP-e4GuBLMt7WpNZnIM1:1 [11:22:06 GMT+0545 (Nepal Standard Time)] SignalR: Triggering client hub event 'updateUsers' on hub 'NotificationsHub'.
master-page.js:201 SignalR connection established with the server
master-page.js:163 succesfully got todays notifications from database
master-page.js:165 [Object]
jquery?v=-DkGyEJfRZ6dUWcIU0eRwmyvX5dxdPO9NsuEY0mWpJM1:1 GET http://everest.planetearthsolution.com/bundles/images/ui-bg_glass_75_dadada_1x400.png 404 (Not Found)it @ jquery?v=-DkGyEJfRZ6dUWcIU0eRwmyvX5dxdPO9NsuEY0mWpJM1:1i.extend.css @ jquery?v=-DkGyEJfRZ6dUWcIU0eRwmyvX5dxdPO9NsuEY0mWpJM1:1tt @ jquery?v=-DkGyEJfRZ6dUWcIU0eRwmyvX5dxdPO9NsuEY0mWpJM1:1ru @ jquery?v=-DkGyEJfRZ6dUWcIU0eRwmyvX5dxdPO9NsuEY0mWpJM1:1i.fn.extend.hide @ jquery?v=-DkGyEJfRZ6dUWcIU0eRwmyvX5dxdPO9NsuEY0mWpJM1:1i.each.i.fn.(anonymous function) @ jquery?v=-DkGyEJfRZ6dUWcIU0eRwmyvX5dxdPO9NsuEY0mWpJM1:1n.fn.extend.hide @ js?v=L_9r91gHO7EXWDPucYBWepNDN6FfKO6Vh0ohPWu-CbY1:1n.widget.__response @ js?v=L_9r91gHO7EXWDPucYBWepNDN6FfKO6Vh0ohPWu-CbY1:1(anonymous function) @ js?v=L_9r91gHO7EXWDPucYBWepNDN6FfKO6Vh0ohPWu-CbY1:1(anonymous function) @ js?v=L_9r91gHO7EXWDPucYBWepNDN6FfKO6Vh0ohPWu-CbY1:1i.extend.proxy.i.isFunction.r @ jquery?v=-DkGyEJfRZ6dUWcIU0eRwmyvX5dxdPO9NsuEY0mWpJM1:1$.ajax.success @ autocomplete-loan.js:34i.Callbacks.l @ jquery?v=-DkGyEJfRZ6dUWcIU0eRwmyvX5dxdPO9NsuEY0mWpJM1:1i.Callbacks.s.fireWith @ jquery?v=-DkGyEJfRZ6dUWcIU0eRwmyvX5dxdPO9NsuEY0mWpJM1:1p @ jquery?v=-DkGyEJfRZ6dUWcIU0eRwmyvX5dxdPO9NsuEY0mWpJM1:1i.ajaxTransport.send.t @ jquery?v=-DkGyEJfRZ6dUWcIU0eRwmyvX5dxdPO9NsuEY0mWpJM1:1
master-page.js:44 inside ajaxstarted function
master-page.js:46 inside the condition
master-page.js:52 inside ajaxstarted function
LoanReimburse.aspx:1 Uncaught SyntaxError: Unexpected token E
signalr?v=y_4IpeeDdgoHqAhjqu2f3QsBnP-e4GuBLMt7WpNZnIM1:1 [11:23:18 GMT+0545 (Nepal Standard Time)] SignalR: Triggering client hub event 'updateUsers' on hub 'NotificationsHub'.
signalr?v=y_4IpeeDdgoHqAhjqu2f3QsBnP-e4GuBLMt7WpNZnIM1:1 [11:23:21 GMT+0545 (Nepal Standard Time)] SignalR: Triggering client hub event 'updateUsers' on hub 'NotificationsHub'.
signalr?v=y_4IpeeDdgoHqAhjqu2f3QsBnP-e4GuBLMt7WpNZnIM1:1 [11:23:24 GMT+0545 (Nepal Standard Time)] SignalR: Triggering client hub event 'updateUsers' on hub 'NotificationsHub'.

**Comment by nabinked** [comment]
Problem is solved.
